version: "3"

services:

  ebusd:
    image: lukics/ebusd:armv7
    networks:
      - monitor
      - proxy
    command: 
      - "-f"
      - "--pollinterval=1" 
      - "--latency=1000"
      - "--httpport=8085"
      - "--scanconfig" 
      - "--mqtthost=192.168.3.67"
      - "--mqttport=1884"
      - "--enablehex"
      - "-d 192.168.3.35:5000"
      - "--loglevel=info"
    volumes:
      - /datavol/ebusd/encon:/etc/ebusd/encon
      - /datavol/ebusd/log/:/var/log
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath.1=/ebusd
        - com.df.reqPathSearchReplace.1=^/ebusd/?,/
        - com.df.port.1=8085
        - com.df.srcPort.2=1884
        - com.df.port.2=1884
        - com.df.reqMode.2=tcp
        - com.df.srcPort.3=8888
        - com.df.port.3=8888
        - com.df.reqMode.3=tcp
networks:
  monitor:
    external: true
  proxy:
    external: true  
