version: "3"

services:

  ebusd:
    image: lukics/ebusd-3.3:armv7
    networks:
      - monitor
      - proxy
    ports:
      - 8888:8888
      - 8085:8085
    command: 
      - "-f"
      - "--latency=10000"
      - "--httpport=8085"
      - "--scanconfig" 
      - "--mqtthost=vevedock"
      - "--mqttport=1883"
      - "--enablehex"
      - "--device=eBusGW:5000"
      - "--configpath=/etc/ebusd/encon"
      - "--loglevel=info"
      - "--pollinterval=1"
    volumes:
#      - /datavol/ebusd/encon:/etc/ebusd/encon
      - /datavol/ebusd/log/:/var/log
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath.1=/ebusd
        - com.df.reqPathSearchReplace.1=^/ebusd/?,/
        - com.df.port.1=8085
        - com.df.srcPort.2=8888
        - com.df.port.2=8888
        - com.df.reqMode.2=tcp
networks:
  monitor:
    external: true
  proxy:
    external: true  
