version: '3.6'
services:
  glusterfs:
    privileged: true
    restart: always
    network_mode: host
    tty: true
    image: 'lukics/glusterfs:armv7'
    container_name: glusterfs-${HOST}
    volumes:
      - /opt/gluster/glusterd:/var/lib/glusterd:z
      - /opt/gluster/logs:/var/log/glusterfs:z
      - /media/stick-01:/bricks
#      - /media/ssd-01:/bricks
