version: "3"

services:

  frontail:
    image: lukics/frontail:linux-arm32v7-latest
    networks:
      - monitor
      - proxy
    volumes:
      - /tmp/oh/openhab_userdata:/openhab/userdata
    command:
      - /openhab/userdata/logs/events.log  
      - /openhab/userdata/logs/openhab.log
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/oh-log/
        - com.df.port=9001


networks:
  monitor:
    external: true
  proxy:
    external: true  
