version: "3.3"

services:

  glustercl:
    privileged: true
    restart: always
    image: lukics/glustercl:armv7
    networks:
      - monitor
    environment:
      - LC_SRV=vevedock-02
      - GVOL=vol
      - LC_DIR=/mnt4711
    volumes:
      - shd:/mnt4711
      
    
    labels:
      - com.df.notify=true
      - com.df.distribute=true
    
volumes:
  shd:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt4711    

networks:
  monitor:
    external: true
    
