version: "3.3"

services:

  glustercl:
    privileged: true
    restart: always
    image: lukics/glustercl:armv7
    networks:
      - monitor
    environment:
      - LC_SRV=vevedock-02
      - GVOL=vol
      - LC_DIR=/mnt4711
    volumes:
      - type: bind
        source: /mnt4711
        target: /mnt4711
        bind:
          propagation: shared    
    labels:
      - com.df.notify=true
      - com.df.distribute=true
    
networks:
  monitor:
    external: true
    
