version: "3.3"

services:

  glustercl:
    privileged: true
    restart: always
    image: lukics/glustercl:armv7
    networks:
      - monitor
    environment:
      - LC_SRV=vevedock-02
      - GVOL=vol
      - LC_DIR=/mount-on-container
    volumes:
      - type: volume
        source: /etc/hostname
        target: /etc/hostname-host
      - type: bind
        source: /mnt-on-host
        target: /mount-on-container
        bind:
          propagation: rshared    
    labels:
      - com.df.notify=true
      - com.df.distribute=true
    
networks:
  monitor:
    external: true
    
