version: "3.3"

services:

  glustercl:
    privileged: true
    restart: always
    image: lukics/glustercl:armv7
    networks:
      - monitor
    environment:
      # local container server. set automatically if omitten to host running container
#      - LC_SRV=vevedock-02
      # gluster volume
      - GVOL=vol
      # local directory on container $GVOL sould be mounted
      - LC_DIR=/mount-on-container
      # local directory on container host $LC_DIR sould be mounted
      - LH_DIR=/mnt-on-host
    volumes:
      - /etc/hostname:/etc/hostname-host
      - type: bind
        source: $LH_DIR
        target: $LC_DIR
        bind:
          propagation: rshared    
    labels:
      - com.df.notify=true
      - com.df.distribute=true
    
networks:
  monitor:
    external: true
