version: "3.3"

services:

  glustercl:
    privileged: true
    restart: always
    image: lukics/glustercl:armv7
    networks:
      - monitor
    environment:
      - LC_SRV=vevedock-02
      - GVOL=vol
      - LC_DIR=/mnt4711
    volumes:
      - host_path: /mnt4711
      container_path: /mnt4711
      options: 
      - "rw"
      - "rshared"        
    labels:
      - com.df.notify=true
      - com.df.distribute=true

networks:
  monitor:
    external: true
    
