version: "3"

services:

  influxdb:
    image: influxdb
    networks:
      - monitor
      - proxy
    volumes:
      - /datavol/influxdb:/etc/influxdb
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath.1=/influxdb
        - com.df.reqPathSearchReplace.1=/influxdb,/
        - com.df.port.1=8086
        - com.df.srcPort.2=8086
        - com.df.port.2=8086
        - com.df.reqMode.2=tcp
networks:
  monitor:
    external: true
  proxy:
    external: true  
