version: "3"

services:

  openhab:
    image: openhab/openhab:2.4.0
    networks:
      - monitor
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /tmp/oh/openhab_addons:/openhab/addons
      - /tmp/oh/openhab_conf:/openhab/conf
      - /tmp/oh/openhab_userdata:/openhab/userdata
      - /tmp/oh/backup:/backups
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/openhab/
        - com.df.reqPathSearch=/openhab
        - com.df.port=8080
  
  frontail:
    image: lukics/frontail:linux-arm32v7-latest
    networks:
      - monitor
      - proxy
    volumes:
      - /tmp/oh/openhab_userdata:/openhab/userdata
    command:
      - --url-path /oh-log
      - /openhab/userdata/logs/events.log  
      - /openhab/userdata/logs/openhab.log
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/oh-log
        - com.df.port=9001


networks:
  monitor:
    external: true
  proxy:
    external: true  
