version: "3"

services:

  openhab:
    image: openhab/openhab:2.4.0
    networks:
      - monitor
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /datavol/openhab/openhab_addons:/openhab/addons \
      - /datavol/openhab/openhab_conf:/openhab/conf \
      - /datavol/openhab/openhab_userdata:/openhab/userdata 
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin
    labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.servicePath=/openhab/
      - com.df.reqPathSearch=/openhab
      - com.df.port=8080
  
networks:
  monitor:
    external: true
  proxy:
    external: true  
