version: '3'

services:
  openhab:
    image: "openhab/openhab:2.4.0"
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
      - ./openhab_addons:/openhab/addons
      - ./openhab_conf:/openhab/conf
      - ./openhab_userdata:/openhab/userdata
      - ./backup:/backups
    networks:
      - openhab_net

networks:
  openhab_net:
