version: '3'
services:
  test1:
    image: nginx:stable-alpine
    networks:
      - macnet3:
        ipv4_address: 192.168.3.10
   
  test2:
    image: nginx:stable-alpine
    networks:
      - macnet3
        ipv4_address: 192.168.3.11
   
networks:
 macnet3:
   external:
     name: macnet3
