version: "3"

services:

  grafana:
    image: lukics/grafana:5.4.2
    networks:
      - monitor
      - proxy
    volumes:
      - /datavol/grafana/etc:/etc/grafana
      - /datavol/grafana/lib:/var/lib/grafana
#      - /datavol/grafana/share:/usr/share/grafana
    environment:
      - GF_SERVER_DOMAIN=${DOMAIN:-localhost}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS:-admin}
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/grafana/, /grafana
        - com.df.reqPathSearchReplace=/grafana
        - com.df.port=3000
#        - com.df.servicePath.1=/openhab,/rest,/start,/habpanel,/habmin,/doc,/paperui
#        - com.df.reqPathSearchReplace.1=/openhab,/

networks:
  monitor:
    external: true
  proxy:
    external: true  
