version: '3.3'
services:
    glustercl:
        privileged: true
        restart: always
        image: 'lukics/glustercl:armv7'
        environment:
            - LC_SRV=vevedock
            - GVOL
            - LC_DIR=/datavol
            - LH_DIR=/datavol
        volumes:
            - {type: bind, source: '${LH_DIR}', target: '${LC_DIR}', bind: {propagation: rshared}}
        labels:
            - com.df.notify=true
            - com.df.distribute=true
