version: '3.3'
services:
    glustercl:
        privileged: true
        restart: always
        image: 'lukics/glustercl:armv7'
        networks:
            - monitor
            - glsnet        environment:
            - LC_SRV=glusterfs-${HOSTNAME}
            - GVOL
            - LC_DIR
            - LH_DIR
        volumes:
            - {type: bind, source: '${LH_DIR}', target: '${LC_DIR}', bind: {propagation: rshared}}
        labels:
            - com.df.notify=true
            - com.df.distribute=true
networks:
    monitor:
        external: true
    glsnet:
        external: true
