version: "3"

volumes:
  openhab-log:

services:

  openhab:
    image: openhab/openhab:2.4.0
    hostname: openhab
    networks:
      - monitor
      - proxy     
# on empty not initialized OH instance (empty directories)
# run with disabled vlan
      - oh_vlan
    ports:
      - 9125:9125
      - 9126:9126
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /datavol/openhab/openhab_addons:/openhab/addons 
      - /datavol/openhab/openhab_conf:/openhab/conf 
      - /datavol/openhab/openhab_userdata:/openhab/userdata 
      - openhab-log:/openhab/userdata/logs
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443
      - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin -Xms400m -Xmx650m
      - CRYPTO_POLICY=unlimited
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
#        - com.df.servicePath.1=/openhab,/rest,/start,/habpanel,/habmin,/doc,/paperui
        - com.df.servicePath.1=/openhab,/openhab/
        - com.df.reqPathSearchReplace.1=^/openhab/?,/
        - com.df.port.1=8080
        - com.df.srcPort.2=9125
        - com.df.port.2=9125
        - com.df.reqMode.2=tcp
        - com.df.srcPort.3=9126
        - com.df.port.3=9126
        - com.df.reqMode.3=tcp
 
  frontail:
    image: lukics/frontail:linux-arm32v7-latest
    networks:
      - monitor
      - proxy
    volumes_from:
      - openhab
    volumes:
      - /datavol/openhab/openhab_userdata:/openhab/userdata
    command:
      - --url-path /oh-log
      - /openhab/userdata/logs/events.log  
      - /openhab/userdata/logs/openhab.log
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/oh-log
        - com.df.port=9001


networks:
  monitor:
    external: true
  proxy:
    external: true  
  oh_vlan:
    external: true  
