version: '3.3'
services:
    glustercl:
        privileged: true
        restart: always
        image: 'lukics/glustercl:armv7'
        networks:
            - monitor
            - glsnet  
            - bridge
        environment:
            - LC_SRV=vevedock
            - GVOL=vol
            - LC_DIR=/datavol
            - LH_DIR=/datavol
        volumes:
            - {type: bind, source: '/datavol', target: '/datavol', bind: {propagation: rshared}}
        deploy:
            mode: global
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                
networks:
    monitor:
        external: true
    glsnet:
        external: true
    bridge:
        external: true
