version: '3.3'
services:
    glusterfs:
        privileged: true
        restart: always
        image: 'lukics/glusterfs:armv7'
#        command: sleep 100000
        container_name: glusterfs-${HOSTNAME}
        networks:
            - monitor
            - glsnet
        environment:
            - HOSTNAME
            - LC_SRV
            - GVOL
            - LC_DIR
            - LH_DIR
        volumes:
            - /media/stick-01:/bricks
#            - {type: bind, source: '/etc/glusterfs', target: '/etc', bind: {propagation: rshared}}
#            - /opt/gluster/glusterfs:/etc/glusterfs:z
            - /opt/gluster/glusterd:/var/lib/glusterd:z
            - /opt/gluster/logs:/var/log/glusterfs:z 
        deploy:
            labels:
                - com.df.notify=true
                - com.df.distribute=true
    glustercl:
        privileged: true
        restart: always
        image: 'lukics/glustercl:armv7'
        networks:
            - monitor
            - glsnet        
        environment:
            - LC_SRV=glusterfs-${HOSTNAME}
            - GVOL
            - LC_DIR
            - LH_DIR
        volumes:
            - {type: bind, source: '${LH_DIR}', target: '${LC_DIR}', bind: {propagation: rshared}}
        deploy:
            labels:
                - com.df.notify=true
                - com.df.distribute=true
                
networks:
    monitor:
        external: true
    glsnet:
        external: true
