version: '2'
services:
    openvpn:
        cap_add:
            - ALL
        restart: always
        image: 'lukics/openvpn:armv7'
        ports:
          - 1194:1194/udp        
        volumes:
          - /datavol/openvpn/etc:/etc/openvpn
