version: '3.3'
services:
    openvpn:
        privileged: true
        restart: always
        image: 'lukics/openvpn:armv7'
        network_mode: host
        ports:
          - 1194:1194/udp        
        volumes:
          - /datavol/openvpn/etc:/etc/openvpn
