version: '3.6'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    network_mode: host
    restart: unless-stopped
    ports:
    - "9080:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /datavol/portainer/data:/data
