version: "3"

services:

  influxdb:
    image: influxdb
    networks:
      - monitor
      - proxy
    command: "-config /etc/influxdb/influxdb.conf"
    volumes:
      - /datavol/influxdb/etc:/etc/influxdb
      - /datavol/influxdb/meta:/var/lib/influxdb/meta
      - /datavol/influxdb/data:/var/lib/influxdb/data
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/influxdb
        - com.df.reqPathSearchReplace=/influxdb/,/
        - com.df.port=8086
networks:
  monitor:
    external: true
  proxy:
    external: true  
