version: '3.3'
services:
    glusterfs:
        privileged: true
        restart: always
        image: 'lukics/glusterfs:armv7'
        container_name: glusterfs-${HOSTNAME}
        networks:
            - monitor
            - glsnet
        environment:
            - HOSTNAME
            - LC_SRV
            - GVOL
            - LC_DIR
            - LH_DIR
        volumes:
            - /bricks:/bricks
            - /etc/glusterfs:/etc:z
            - /var/lib/glusterd:/var/lib/glusterd:z
            - /var/log/glusterfs:/var/log/glusterfs:z 
        labels:
            - com.df.notify=true
            - com.df.distribute=true
networks:
    monitor:
        external: true
    glsnet:
        external: true
        

# docker run -d --net=host --privileged --name gluster -v /data:/data 
# docker run -d --net=host --privileged --name gluster -v /data:/data registry:5000/gluster
# docker run --restart=always --name gfsc1 -v /bricks:/bricks -v /sys/fs/cgroup:/sys/fs/cgroup:ro --mount type=bind,source=/datavol,target=/datavol,bind-propagation=rshared -d --privileged=true --net=netgfs -v /dev/:/dev gluster/gluster-centos
