version: '3.3'
services:
    glusterfs:
        privileged: true
        restart: always
        image: 'lukics/glusterfs:armv7'
#        command: sleep 100000
        container_name: glusterfs-${HOSTNAME}
        networks:
            - monitor
            - glsnet
        environment:
            - HOSTNAME
            - LC_SRV
            - GVOL
            - LC_DIR
            - LH_DIR
        volumes:
            - /media/stick-01:/bricks
#            - {type: bind, source: '/etc/glusterfs', target: '/etc', bind: {propagation: rshared}}
#            - /opt/gluster/glusterfs:/etc/glusterfs:z
            - /opt/gluster/glusterd:/var/lib/glusterd:z
            - /opt/gluster/logs:/var/log/glusterfs:z 
        labels:
            - com.df.notify=true
            - com.df.distribute=true
networks:
    monitor:
        external: true
    glsnet:
        external: true
        

# docker run -d --net=host --privileged --name gluster -v /data:/data 
# docker run -d --net=host --privileged --name gluster -v /data:/data registry:5000/gluster
# docker run --restart=always --name gfsc1 -v /bricks:/bricks -v /sys/fs/cgroup:/sys/fs/cgroup:ro --mount type=bind,source=/datavol,target=/datavol,bind-propagation=rshared -d --privileged=true --net=netgfs -v /dev/:/dev gluster/gluster-centos
